name: Master
on:
  push:
    branches:
      - master

jobs:
  coverage:
    name: "Code coverage"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup environment
        run: |
          make env
          pip install -r requirements-ci.txt

      - name: Coverage Badge
        env:
          PYTHONPATH: $PYTHONPATH:$(pwd)/src/graceful_exit:$(pwd)/src:$(pwd)
        run: |
          pip install -e .
          make test
          make coverage-badge
  changes:
    needs: coverage
    runs-on: ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      coverage-badge: ${{ steps.filter.outputs.coverage-badge }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          list-files: "json"
          filters: |
            coverage-badge:
              - '.'

  commit-badge:
    needs: changes
    if: ${{ needs.changes.outputs.coverage-badge == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}
